// eslint-disable-next-line no-unused-vars
const ChainData = {
  Elrond: {
    node_uri: "string",
    minter_address: "string",
    esdt_swap_address: "string",
    esdt: "string",
    esdt_nft: "string",
    esdt_swap: "string",
    validators: "string[]",
    nonce: "number",
  },
  Tron: {
    provider: "TronWeb",
    middleware_uri: "string",
    erc1155_addr: "string",
    minter_addr: "string",
    erc721_addr: "string",
    validators: "string[]",
    nonce: "number",
  },
  Avalanche: {
    provider: "JsonRpcProvider",
    minter_addr: "string",
    erc1155_addr: "string",
    erc721_addr: "string",
    validators: "string[]",
    nonce: "number",
  },
  Polygon: {
    provider: "JsonRpcProvider",
    minter_addr: "string",
    erc1155_addr: "string",
    erc721_addr: "string",
    validators: "string[]",
    nonce: "number",
  },
  Fantom: {
    provider: "JsonRpcProvider",
    minter_addr: "string",
    erc1155_addr: "string",
    erc721_addr: "string",
    validators: "string[]",
    nonce: "number",
  },
  Celo: {
    provider: "JsonRpcProvider",
    minter_addr: "string",
    erc1155_addr: "string",
    erc721_addr: "string",
    validators: "string[]",
    nonce: "number",
  },
  Harmony: {
    provider: "JsonRpcProvider",
    minter_addr: "string",
    erc1155_addr: "string",
    erc721_addr: "string",
    validators: "string[]",
    nonce: "number",
  },
  Ropsten: {
    provider: "JsonRpcProvider",
    minter_addr: "string",
    erc1155_addr: "string",
    erc721_addr: "string",
    validators: "string[]",
    nonce: "number",
  },
};
